-- create cumulating user activity table by device
CREATE
OR REPLACE TABLE RGINDALLAS.USER_DEVICES_CUMULATED (
    USER_ID BIGINT,
    BROWSER_TYPE VARCHAR,
    DATES_ACTIVE ARRAY(DATE),
    DATE DATE
)
WITH
    (FORMAT='PARQUET', PARTITIONING=ARRAY['date'])
