CREATE
OR REPLACE TABLE RGINDALLAS.HOST_ACTIVITY_REDUCED (
    HOST VARCHAR,
    METRIC_NAME VARCHAR,
    METRIC_ARRAY ARRAY(INTEGER),
    MONTH_START VARCHAR
)
WITH
    (
        FORMAT='PARQUET',
        PARTITIONING=ARRAY['metric_name', 'month_start']
    )
