CREATE
OR REPLACE TABLE RGINDALLAS.HOSTS_CUMULATED (
    HOST VARCHAR,
    HOST_ACTIVITY_DATELIST ARRAY(DATE),
    DATE DATE
)
WITH
    (FORMAT='PARQUET', PARTITIONING=ARRAY['date'])
    -- tag for feedback
